const body = {
  ublVersion: '2.1',
  fecVencimiento: '2021-01-27T00:00:00-05:00',
  tipoOperacion: '0101',
  tipoDoc: '01',
  serie: 'F001',
  correlativo: '123',
  fechaEmision: '2021-01-27T00:00:00-05:00',
  formaPago: {
    moneda: 'PEN',
    tipo: 'Contado',
  },
  tipoMoneda: 'PEN',
  client: {
    tipoDoc: '6',
    numDoc: 20000000002,
    rznSocial: 'Cliente',
    address: {
      direccion: 'Direccion cliente',
      provincia: 'LIMA',
      departamento: 'LIMA',
      distrito: 'LIMA',
      ubigueo: '150101',
    },
  },
  company: {
    ruc: 20610999999,
    razonSocial: 'Mi empresa',
    nombreComercial: 'Mi empresa',
    address: {
      direccion: 'Direccion empresa',
      provincia: 'LIMA',
      departamento: 'LIMA',
      distrito: 'LIMA',
      ubigueo: '150101',
    },
  },
  mtoOperGravadas: 200,
  mtoOperExoneradas: 100,
  mtoIGV: 36,
  totalImpuestos: 36,
  valorVenta: 300,
  subTotal: 336,
  mtoImpVenta: 336,
  details: [
    {
      codProducto: 'P001',
      unidad: 'NIU',
      descripcion: 'PRODUCTO 1',
      cantidad: 2,
      mtoValorUnitario: 100,
      mtoValorVenta: 200,
      mtoBaseIgv: 200,
      porcentajeIgv: 18,
      igv: 36,
      tipAfeIgv: 10,
      totalImpuestos: 36,
      mtoPrecioUnitario: 118,
    },
    {
      codProducto: 'P002',
      unidad: 'KG',
      descripcion: 'PRODUCTO 2',
      cantidad: 2,
      mtoValorUnitario: 50,
      mtoValorVenta: 100,
      mtoBaseIgv: 100,
      porcentajeIgv: 0,
      igv: 0,
      tipAfeIgv: 20,
      totalImpuestos: 0,
      mtoPrecioUnitario: 50,
    },
  ],
  legends: [
    {
      code: '1000',
      value: 'SON TRESCIENTOS TREINTA Y SEIS CON OO/100 SOLES',
    },
  ],
}
